services:
  points-service:
    build: ./points-service
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DB: db
    volumes:
      - ./points-service:/app
    working_dir: /app
    ports:
      - 8081:8080
    depends_on:
      - db
      - adminer

  alerts-service:
    build: ./alerts-service
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DB: db
    volumes:
      - ./alerts-service:/app
    working_dir: /app
    ports:
      - 8082:8080
    depends_on:
      - db
      - adminer
      - rabbitmq

  auth-service:
    build: ./auth-service
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DB: db
    volumes:
      - ./auth-service:/app
    working_dir: /app
    ports:
      - 8083:8080
    depends_on:
      - db
      - adminer

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
