services:
  points-service:
    build: ./points-service
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DB: db
    volumes:
      - ./points-service:/app
    working_dir: /app
    ports:
      - 8081:8080
    depends_on:
      - db
      - adminer

  db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # Exposes NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount custom NGINX configuration
    depends_on:
      - points-service
      - db
      - adminer
