server:
  host: 0.0.0.0
  port: 8080

rabbitmq:
  exchange:
    name: "exchange"
    type: "direct"
    durability: true
  queue1:
    name: "alerts"
    durability: true
    key: "alert"
  queue2:
    name: "notifications"
    durability: true
    key: "notification"
